import mongoose from 'mongoose';
import dotenv from 'dotenv';
import bcrypt from 'bcryptjs';

import { connectDB } from '../config/database.js';
import { User } from '../models/User.js';
import { Movie } from '../models/Movie.js';
import { Theatre } from '../models/Theatre.js';
import { Screen } from '../models/Screen.js';
import { Seat } from '../models/Seat.js';
import { Show } from '../models/Show.js';
import { Booking } from '../models/Booking.js';
import { Payment } from '../models/Payment.js';
import { Coupon } from '../models/Coupon.js';
import { Review } from '../models/Review.js';
import { generateBookingReference } from '../utils/generateBookingReference.js';
import { generateQRCode } from '../utils/generateQRCode.js';
import { enrichWithIMDbData } from './imdbCatalog.js';

dotenv.config();

const seedDatabase = async (isStandalone = true) => {
  try {
    await connectDB();
    console.log('[Seed] Clearing existing database collections...');

    await Promise.all([
      User.deleteMany({}),
      Movie.deleteMany({}),
      Theatre.deleteMany({}),
      Screen.deleteMany({}),
      Seat.deleteMany({}),
      Show.deleteMany({}),
      Booking.deleteMany({}),
      Payment.deleteMany({}),
      Coupon.deleteMany({}),
      Review.deleteMany({}),
    ]);

    console.log('[Seed] Seeding Users...');
    const admin = await User.create({
      name: 'SmartCine Admin',
      email: 'admin@smartcine.com',
      password: 'Admin@12345',
      phone: '+91 9988776655',
      role: 'admin',
      preferredCity: 'Hyderabad',
      profileImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      isActive: true,
    });

    const customer = await User.create({
      name: 'Aarav Sharma',
      email: 'customer@smartcine.com',
      password: 'Customer@12345',
      phone: '+91 9876543210',
      role: 'customer',
      preferredCity: 'Hyderabad',
      profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      isActive: true,
    });

    const customer2 = await User.create({
      name: 'Priya Patel',
      email: 'priya@smartcine.com',
      password: 'Customer@12345',
      phone: '+91 9823456789',
      role: 'customer',
      preferredCity: 'Bengaluru',
      profileImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
      isActive: true,
    });

    // ════════════════════════════════════════════════════════════
    // MOVIES — 55+ Indian & International titles
    // ════════════════════════════════════════════════════════════
    console.log('[Seed] Seeding 55+ Movies...');
    const moviesData = [
      // ── TELUGU NOW SHOWING ────────────────────────────────
      {
        title: 'Pushpa 2: The Rule',
        originalTitle: 'Pushpa 2: The Rule',
        description: 'Pushpa Raj expands his red sandalwood empire while clashing with SP Bhanwar Singh Shekhawat in a battle for supremacy.',
        poster: 'https://image.tmdb.org/t/p/w500/b0OnvU5xV5xZ2K2QYgL9uU1dI9c.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/9wSbeLhhQvE8uG020R4R0pLzWw1.jpg',
        trailerUrl: 'https://www.youtube.com/watch?v=g3JUbgOIe1Q',
        genre: ['Action', 'Crime', 'Drama'],
        language: ['Telugu'],
        originalLanguage: 'Telugu',
        industry: 'Tollywood',
        languages: ['Telugu', 'Hindi'],
        duration: 200,
        certification: 'UA',
        releaseDate: new Date('2026-08-29'),
        cast: ['Allu Arjun', 'Rashmika Mandanna', 'Fahadh Faasil', 'Jagapathi Babu'],
        director: 'Sukumar',
        rating: 4.9,
        ratingCount: 3450,
        status: 'now-showing',
        formats: ['2D', '3D', 'IMAX'],
        source: 'seed',
        isFeatured: true,
        isTrending: true,
        viewCount: 45200,
        country: 'IN',
      },
      {
        title: 'Devara: Part 1',
        description: 'An epic action saga set against the coastal lands where fear and courage collide across generations.',
        poster: 'https://image.tmdb.org/t/p/w500/A7341k5wBwWc5yYk9z6qA5g5s0M.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/tElnmtp6DY1P0TXp84guEjVMBBp.jpg',
        trailerUrl: 'https://www.youtube.com/watch?v=Nn_r5bN9V4k',
        genre: ['Action', 'Drama', 'Thriller'],
        language: ['Telugu'],
        originalLanguage: 'Telugu',
        industry: 'Tollywood',
        languages: ['Telugu', 'Hindi'],
        duration: 178,
        certification: 'UA',
        releaseDate: new Date('2026-09-05'),
        cast: ['N.T. Rama Rao Jr.', 'Janhvi Kapoor', 'Saif Ali Khan', 'Prakash Raj'],
        director: 'Koratala Siva',
        rating: 4.6,
        ratingCount: 1670,
        status: 'now-showing',
        formats: ['2D', '3D', 'IMAX'],
        source: 'seed',
        isTrending: true,
        viewCount: 32100,
        country: 'IN',
      },
      {
        title: 'Kalki 2898 AD',
        description: 'Set in a post-apocalyptic world in the year 2898 AD, a modern avatar of Vishnu descends to Earth to protect the world from evil forces.',
        poster: 'https://image.tmdb.org/t/p/w500/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/9l1eZiJHmhr5jA67VP5q7W9SQRI.jpg',
        trailerUrl: 'https://www.youtube.com/watch?v=kQDd1AhGIHk',
        genre: ['Sci-Fi', 'Action', 'Fantasy'],
        language: ['Telugu'],
        originalLanguage: 'Telugu',
        industry: 'Tollywood',
        languages: ['Telugu', 'Hindi'],
        duration: 180,
        certification: 'UA',
        releaseDate: new Date('2026-08-15'),
        cast: ['Prabhas', 'Amitabh Bachchan', 'Kamal Haasan', 'Deepika Padukone'],
        director: 'Nag Ashwin',
        rating: 4.8,
        ratingCount: 1420,
        status: 'now-showing',
        formats: ['2D', '3D', 'IMAX'],
        source: 'seed',
        isFeatured: true,
        viewCount: 52800,
        country: 'IN',
      },
      {
        title: 'Sita Ramam',
        description: 'A love story set during the 1960s Indo-Pak war, where a soldier receives an anonymous love letter from a woman named Sita.',
        poster: 'https://image.tmdb.org/t/p/w500/7qlcz0VlQu4K7xYmq3T4SH5bUHt.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/q5Sw9c22YBtRmrJdL8SCqCQdPjY.jpg',
        trailerUrl: 'https://www.youtube.com/watch?v=Rwrj4j8XxR8',
        genre: ['Romance', 'Drama', 'War'],
        language: ['Telugu'],
        originalLanguage: 'Telugu',
        industry: 'Tollywood',
        languages: ['Telugu', 'Hindi'],
        duration: 163,
        certification: 'U',
        releaseDate: new Date('2026-09-12'),
        cast: ['Dulquer Salmaan', 'Mrunal Thakur', 'Rashmika Mandanna', 'Sumanth'],
        director: 'Hanu Raghavapudi',
        rating: 4.7,
        ratingCount: 2800,
        status: 'now-showing',
        formats: ['2D'],
        source: 'seed',
        viewCount: 18500,
        country: 'IN',
      },
      {
        title: 'Salaar: Part 2 - Shouryaanga Parvam',
        description: 'The continuation of the saga where Deva and Vardha face new threats in the deadly power struggle of the tribal kingdom.',
        poster: 'https://image.tmdb.org/t/p/w500/dOGMwCgfGMKKx5RVGFmHSutwqfq.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/bQS43HSLZzMjZkcHJz4fGc3DMHB.jpg',
        trailerUrl: 'https://www.youtube.com/watch?v=salaar2trailer',
        genre: ['Action', 'Thriller', 'Drama'],
        language: ['Telugu'],
        originalLanguage: 'Telugu',
        industry: 'Tollywood',
        languages: ['Telugu', 'Hindi'],
        duration: 175,
        certification: 'UA',
        releaseDate: new Date('2026-09-18'),
        cast: ['Prabhas', 'Prithviraj Sukumaran', 'Shruti Haasan', 'Jagapathi Babu'],
        director: 'Prashanth Neel',
        rating: 4.5,
        ratingCount: 890,
        status: 'now-showing',
        formats: ['2D', '3D', 'IMAX'],
        source: 'seed',
        isFeatured: true,
        isTrending: true,
        viewCount: 61000,
        country: 'IN',
      },
      {
        title: 'Game Changer',
        description: 'An IAS officer battles a corrupt political dynasty to reform the electoral system, challenging a powerful chief minister.',
        poster: 'https://image.tmdb.org/t/p/w500/4cR2qVBqMHjO6RHGx6W1RZyxKz2.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/zK3aG3p8cUjfXl0rOKaQeM1bwXv.jpg',
        trailerUrl: 'https://www.youtube.com/watch?v=gamechanger',
        genre: ['Action', 'Drama', 'Thriller'],
        language: ['Telugu'],
        originalLanguage: 'Telugu',
        industry: 'Tollywood',
        languages: ['Telugu', 'Hindi'],
        duration: 165,
        certification: 'UA',
        releaseDate: new Date('2026-09-01'),
        cast: ['Ram Charan', 'Kiara Advani', 'S.J. Suryah', 'Anjali'],
        director: 'S. Shankar',
        rating: 4.3,
        ratingCount: 1200,
        status: 'now-showing',
        formats: ['2D', '3D', 'IMAX'],
        source: 'seed',
        viewCount: 28900,
        country: 'IN',
      },
      {
        title: 'Bhagavanth Kesari',
        description: 'A righteous man fights for justice against a powerful criminal, putting his family at risk in this action drama.',
        poster: 'https://image.tmdb.org/t/p/w500/rO3sDaLnXuU6QPLEd00f7i8b3c4.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/bVTrOWjGLu6dS5ZrXRQ0j0GHeJA.jpg',
        trailerUrl: '',
        genre: ['Action', 'Drama'],
        language: ['Telugu'],
        originalLanguage: 'Telugu',
        industry: 'Tollywood',
        languages: ['Telugu', 'Hindi'],
        duration: 155,
        certification: 'UA',
        releaseDate: new Date('2026-08-22'),
        cast: ['Nandamuri Balakrishna', 'Sreeleela', 'Arjun Rampal'],
        director: 'Anil Ravipudi',
        rating: 4.1,
        ratingCount: 950,
        status: 'now-showing',
        formats: ['2D'],
        source: 'seed',
        viewCount: 12300,
        country: 'IN',
      },

      // ── HINDI NOW SHOWING ─────────────────────────────────
      {
        title: 'Stree 3',
        description: 'The residents of Chanderi face a new supernatural threat more terrifying than ever, leading them to reunite for another hilarious horror adventure.',
        poster: 'https://image.tmdb.org/t/p/w500/mifGKiCGRsu39V6zNxFSXzE3UNl.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
        trailerUrl: 'https://www.youtube.com/watch?v=stree3',
        genre: ['Horror', 'Comedy'],
        language: ['Hindi'],
        originalLanguage: 'Hindi',
        industry: 'Bollywood',
        languages: ['Hindi'],
        duration: 152,
        certification: 'UA',
        releaseDate: new Date('2026-09-10'),
        cast: ['Rajkummar Rao', 'Shraddha Kapoor', 'Pankaj Tripathi', 'Aparshakti Khurana'],
        director: 'Amar Kaushik',
        rating: 4.4,
        ratingCount: 2100,
        status: 'now-showing',
        formats: ['2D', '3D'],
        source: 'seed',
        isTrending: true,
        viewCount: 39400,
        country: 'IN',
      },
      {
        title: 'War 2',
        description: 'India\'s top spy returns for an even deadlier mission that takes him across continents in a race against time.',
        poster: 'https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/yDHYTfA3R0jFYba16jBB1jv82E9.jpg',
        trailerUrl: 'https://www.youtube.com/watch?v=war2trailer',
        genre: ['Action', 'Thriller', 'Espionage'],
        language: ['Hindi'],
        originalLanguage: 'Hindi',
        industry: 'Bollywood',
        languages: ['Hindi'],
        duration: 158,
        certification: 'UA',
        releaseDate: new Date('2026-09-15'),
        cast: ['Hrithik Roshan', 'Jr NTR', 'Kiara Advani'],
        director: 'Ayan Mukerji',
        rating: 4.6,
        ratingCount: 1800,
        status: 'now-showing',
        formats: ['2D', 'IMAX', '4DX'],
        source: 'seed',
        isFeatured: true,
        isTrending: true,
        viewCount: 47800,
        country: 'IN',
      },
      {
        title: 'Singham Again',
        description: 'The fearless cop Bajirao Singham leads an epic mission with India\'s most formidable officers against a global threat.',
        poster: 'https://image.tmdb.org/t/p/w500/6Wdl9N9dOJXgEKtu0P4PyAgbtHj.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/wNXMDOxNOB8lXQ3o0fYVEFxMJdE.jpg',
        trailerUrl: 'https://www.youtube.com/watch?v=singham_again',
        genre: ['Action', 'Drama', 'Thriller'],
        language: ['Hindi'],
        originalLanguage: 'Hindi',
        industry: 'Bollywood',
        languages: ['Hindi'],
        duration: 168,
        certification: 'UA',
        releaseDate: new Date('2026-08-25'),
        cast: ['Ajay Devgn', 'Deepika Padukone', 'Ranveer Singh', 'Akshay Kumar', 'Tiger Shroff'],
        director: 'Rohit Shetty',
        rating: 4.2,
        ratingCount: 3800,
        status: 'now-showing',
        formats: ['2D', '3D', 'IMAX'],
        source: 'seed',
        viewCount: 35600,
        country: 'IN',
      },
      {
        title: 'Bhool Bhulaiyaa 3',
        description: 'Rooh Baba is back! A new haunted haveli, a new mystery, and twice the madness in this supernatural comedy.',
        poster: 'https://image.tmdb.org/t/p/w500/c2UQ5R0s4nVWvEEE1zrXO3Mn10U.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/pTlwPfJQjOhoBnyAJK3jez3z3z3.jpg',
        trailerUrl: '',
        genre: ['Horror', 'Comedy', 'Mystery'],
        language: ['Hindi'],
        originalLanguage: 'Hindi',
        industry: 'Bollywood',
        languages: ['Hindi'],
        duration: 145,
        certification: 'UA',
        releaseDate: new Date('2026-08-30'),
        cast: ['Kartik Aaryan', 'Vidya Balan', 'Madhuri Dixit', 'Triptii Dimri'],
        director: 'Anees Bazmee',
        rating: 4.0,
        ratingCount: 1600,
        status: 'now-showing',
        formats: ['2D', '3D'],
        source: 'seed',
        viewCount: 22100,
        country: 'IN',
      },
      {
        title: 'Dhoom 4',
        description: 'The most daring heist yet as a master thief challenges India\'s toughest cop in a globe-trotting game of cat and mouse.',
        poster: 'https://image.tmdb.org/t/p/w500/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/euYIwmwkmz95mnXvufEmbL69ovr.jpg',
        trailerUrl: '',
        genre: ['Action', 'Thriller', 'Crime'],
        language: ['Hindi'],
        originalLanguage: 'Hindi',
        industry: 'Bollywood',
        languages: ['Hindi'],
        duration: 162,
        certification: 'UA',
        releaseDate: new Date('2026-09-17'),
        cast: ['Shah Rukh Khan', 'Abhishek Bachchan', 'Katrina Kaif'],
        director: 'Ali Abbas Zafar',
        rating: 4.3,
        ratingCount: 500,
        status: 'now-showing',
        formats: ['2D', 'IMAX', '4DX'],
        source: 'seed',
        isTrending: true,
        viewCount: 55000,
        country: 'IN',
      },

      // ── TAMIL NOW SHOWING ─────────────────────────────────
      {
        title: 'Vidaamuyarchi',
        description: 'A man embarks on a relentless journey to find his missing wife, uncovering a dangerous web of deception.',
        poster: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
        trailerUrl: '',
        genre: ['Action', 'Thriller'],
        language: ['Tamil'],
        originalLanguage: 'Tamil',
        industry: 'Kollywood',
        languages: ['Tamil', 'Telugu'],
        duration: 148,
        certification: 'UA',
        releaseDate: new Date('2026-09-08'),
        cast: ['Ajith Kumar', 'Trisha Krishnan', 'Arjun Das'],
        director: 'Magizh Thirumeni',
        rating: 4.2,
        ratingCount: 1100,
        status: 'now-showing',
        formats: ['2D', '3D'],
        source: 'seed',
        viewCount: 19800,
        country: 'IN',
      },
      {
        title: 'Coolie',
        description: 'A powerful underworld drama that follows the rise of a common man in the world of organized crime.',
        poster: 'https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/vL5LR6WdxWPjC3754h62c9Tqg.jpg',
        trailerUrl: '',
        genre: ['Action', 'Crime', 'Drama'],
        language: ['Tamil', 'Telugu', 'Hindi', 'Kannada'],
        duration: 170,
        certification: 'UA',
        releaseDate: new Date('2026-09-14'),
        cast: ['Rajinikanth', 'Shruti Haasan', 'Sathyaraj', 'Upendra'],
        director: 'Lokesh Kanagaraj',
        rating: 4.7,
        ratingCount: 2200,
        status: 'now-showing',
        formats: ['2D', '3D', 'IMAX'],
        source: 'seed',
        isFeatured: true,
        isTrending: true,
        viewCount: 58300,
        country: 'IN',
      },
      {
        title: 'GOAT - Greatest Of All Time',
        description: 'A retired spy is forced back into action when threats from his past resurface, putting both his old and new families in danger.',
        poster: 'https://image.tmdb.org/t/p/w500/hkBq0O3aAwfnPjMCqH3MG8WR0lq.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/vR8bJfSXmTY6KfNk08QMvIBrOHE.jpg',
        trailerUrl: '',
        genre: ['Action', 'Spy', 'Thriller'],
        language: ['Tamil'],
        originalLanguage: 'Tamil',
        industry: 'Kollywood',
        languages: ['Tamil', 'Telugu'],
        duration: 160,
        certification: 'UA',
        releaseDate: new Date('2026-09-05'),
        cast: ['Vijay', 'Prashanth', 'Prabhu Deva', 'Meenakshi Chaudhary'],
        director: 'Venkat Prabhu',
        rating: 4.4,
        ratingCount: 1900,
        status: 'now-showing',
        formats: ['2D', 'IMAX'],
        source: 'seed',
        viewCount: 41200,
        country: 'IN',
      },
      {
        title: 'Vettaiyan',
        description: 'A hard-hitting action thriller about a cop who takes the law into his own hands to deliver justice in a corrupt system.',
        poster: 'https://image.tmdb.org/t/p/w500/xOMo8BRK7PfcJv9JCnx7s520QIq.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s520QIq.jpg',
        trailerUrl: '',
        genre: ['Action', 'Drama'],
        language: ['Tamil'],
        originalLanguage: 'Tamil',
        industry: 'Kollywood',
        languages: ['Tamil', 'Telugu'],
        duration: 155,
        certification: 'UA',
        releaseDate: new Date('2026-08-20'),
        cast: ['Rajinikanth', 'Amitabh Bachchan', 'Fahadh Faasil', 'Rana Daggubati'],
        director: 'T.J. Gnanavel',
        rating: 4.3,
        ratingCount: 1400,
        status: 'now-showing',
        formats: ['2D', '3D'],
        source: 'seed',
        viewCount: 27600,
        country: 'IN',
      },

      // ── MALAYALAM NOW SHOWING ─────────────────────────────
      {
        title: 'Empuraan',
        description: 'The epic sequel to Lucifer — a political powerplay saga that pits family loyalty against ambition in Kerala\'s corridors of power.',
        poster: 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s520QIq.jpg',
        trailerUrl: '',
        genre: ['Action', 'Political', 'Drama'],
        language: ['Malayalam', 'Telugu', 'Tamil', 'Hindi'],
        duration: 185,
        certification: 'UA',
        releaseDate: new Date('2026-09-11'),
        cast: ['Mohanlal', 'Prithviraj Sukumaran', 'Manju Warrier', 'Indrajith Sukumaran'],
        director: 'Prithviraj Sukumaran',
        rating: 4.6,
        ratingCount: 1300,
        status: 'now-showing',
        formats: ['2D', '3D', 'IMAX'],
        source: 'seed',
        isFeatured: true,
        viewCount: 33800,
        country: 'IN',
      },
      {
        title: 'Manjummel Boys',
        description: 'Based on a true story, a group of friends go on a trip to Kodaikanal where one of them gets trapped in a cave, leading to a terrifying rescue mission.',
        poster: 'https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg',
        trailerUrl: '',
        genre: ['Adventure', 'Thriller', 'Drama'],
        language: ['Malayalam', 'Telugu', 'Tamil', 'Hindi'],
        duration: 136,
        certification: 'UA',
        releaseDate: new Date('2026-08-28'),
        cast: ['Soubin Shahir', 'Sreenath Bhasi', 'Balu Varghese'],
        director: 'Chidambaram',
        rating: 4.8,
        ratingCount: 3200,
        status: 'now-showing',
        formats: ['2D'],
        source: 'seed',
        viewCount: 42100,
        country: 'IN',
      },

      // ── KANNADA NOW SHOWING ──────────────────────────────
      {
        title: 'UI',
        description: 'An ambitious visionary sci-fi thriller from the Kannada film industry exploring identity in a dystopian future.',
        poster: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
        trailerUrl: '',
        genre: ['Sci-Fi', 'Drama', 'Thriller'],
        language: ['Kannada', 'Telugu', 'Hindi'],
        duration: 152,
        certification: 'UA',
        releaseDate: new Date('2026-09-16'),
        cast: ['Upendra', 'Reeshma Nanaiah', 'Nidhi Subbaiah'],
        director: 'Upendra',
        rating: 4.1,
        ratingCount: 800,
        status: 'now-showing',
        formats: ['2D', '3D'],
        source: 'seed',
        viewCount: 15400,
        country: 'IN',
      },

      // ── ENGLISH NOW SHOWING ───────────────────────────────
      {
        title: 'Dune: Part Two',
        description: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.',
        poster: 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s520QIq.jpg',
        trailerUrl: 'https://www.youtube.com/watch?v=Way9Dexny3w',
        genre: ['Sci-Fi', 'Adventure', 'Action'],
        language: ['English', 'Hindi'],
        duration: 166,
        certification: 'UA',
        releaseDate: new Date('2026-09-01'),
        cast: ['Timothée Chalamet', 'Zendaya', 'Rebecca Ferguson', 'Javier Bardem', 'Austin Butler'],
        director: 'Denis Villeneuve',
        rating: 4.9,
        ratingCount: 2310,
        status: 'now-showing',
        formats: ['2D', 'IMAX', '4DX'],
        source: 'seed',
        viewCount: 38900,
        country: 'US',
      },
      {
        title: 'Deadpool & Wolverine',
        description: 'A listless Wade Wilson toils away in civilian life until a sudden threat forces him to suit up again alongside an ambivalent Wolverine.',
        poster: 'https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/yDHYTfA3R0jFYba16jBB1jv82E9.jpg',
        trailerUrl: 'https://www.youtube.com/watch?v=73_1biulkYk',
        genre: ['Action', 'Comedy', 'Sci-Fi'],
        language: ['English', 'Hindi', 'Telugu'],
        duration: 128,
        certification: 'A',
        releaseDate: new Date('2026-08-10'),
        cast: ['Ryan Reynolds', 'Hugh Jackman', 'Emma Corrin', 'Matthew Macfadyen'],
        director: 'Shawn Levy',
        rating: 4.7,
        ratingCount: 1890,
        status: 'now-showing',
        formats: ['2D', '3D', 'IMAX'],
        source: 'seed',
        viewCount: 31200,
        country: 'US',
      },
      {
        title: 'Oppenheimer',
        description: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.',
        poster: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg',
        trailerUrl: 'https://www.youtube.com/watch?v=uYPbbksJxIg',
        genre: ['Biography', 'Drama', 'History'],
        language: ['English', 'Hindi'],
        duration: 180,
        certification: 'A',
        releaseDate: new Date('2026-07-21'),
        cast: ['Cillian Murphy', 'Emily Blunt', 'Matt Damon', 'Robert Downey Jr.', 'Florence Pugh'],
        director: 'Christopher Nolan',
        rating: 4.9,
        ratingCount: 4200,
        status: 'now-showing',
        formats: ['2D', 'IMAX'],
        source: 'seed',
        viewCount: 48700,
        country: 'US',
      },
      {
        title: 'Interstellar (IMAX Re-Release)',
        description: 'When Earth becomes uninhabitable, a team of explorers undertakes the most important mission in human history: traveling beyond this galaxy.',
        poster: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
        trailerUrl: 'https://www.youtube.com/watch?v=zSWdZVtXT7E',
        genre: ['Sci-Fi', 'Adventure', 'Drama'],
        language: ['English'],
        originalLanguage: 'English',
        industry: 'Hollywood',
        languages: ['English', 'Hindi', 'Telugu'],
        isDubbed: true,
        dubbedLanguages: ['Hindi', 'Telugu'],
        duration: 169,
        certification: 'UA',
        releaseDate: new Date('2026-09-15'),
        cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain', 'Michael Caine'],
        director: 'Christopher Nolan',
        rating: 5.0,
        ratingCount: 5120,
        status: 'now-showing',
        formats: ['IMAX', '2D'],
        source: 'seed',
        viewCount: 55500,
        country: 'US',
      },
      {
        title: 'Gladiator II',
        description: 'Years after witnessing the death of Maximus, Lucius must enter the Colosseum after his home is conquered by tyrannical emperors.',
        poster: 'https://image.tmdb.org/t/p/w500/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/euYIwmwkmz95mnXvufEmbL69ovr.jpg',
        trailerUrl: 'https://www.youtube.com/watch?v=4rgYUipGJNo',
        genre: ['Action', 'Adventure', 'Drama'],
        language: ['English', 'Hindi'],
        duration: 148,
        certification: 'A',
        releaseDate: new Date('2026-08-05'),
        cast: ['Paul Mescal', 'Pedro Pascal', 'Denzel Washington', 'Connie Nielsen'],
        director: 'Ridley Scott',
        rating: 4.7,
        ratingCount: 1120,
        status: 'now-showing',
        formats: ['2D', 'IMAX', '4DX'],
        source: 'seed',
        viewCount: 24500,
        country: 'US',
      },
      {
        title: 'Thunderbolts*',
        description: 'A group of antiheroes recruited by the government undertake dangerous missions that no ordinary team can handle.',
        poster: 'https://image.tmdb.org/t/p/w500/mifGKiCGRsu39V6zNxFSXzE3UNl.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
        trailerUrl: '',
        genre: ['Action', 'Adventure', 'Sci-Fi'],
        language: ['English', 'Hindi', 'Telugu', 'Tamil'],
        duration: 138,
        certification: 'UA',
        releaseDate: new Date('2026-09-10'),
        cast: ['Florence Pugh', 'Sebastian Stan', 'David Harbour', 'Olga Kurylenko'],
        director: 'Jake Schreier',
        rating: 4.3,
        ratingCount: 900,
        status: 'now-showing',
        formats: ['2D', '3D', 'IMAX'],
        source: 'seed',
        viewCount: 29400,
        country: 'US',
      },
      {
        title: 'A Minecraft Movie',
        description: 'A group of unlikely heroes is pulled into the Overworld, a wild, blocky wonderland that thrives on imagination.',
        poster: 'https://image.tmdb.org/t/p/w500/c2UQ5R0s4nVWvEEE1zrXO3Mn10U.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/pTlwPfJQjOhoBnyAJK3jez3z3z3.jpg',
        trailerUrl: '',
        genre: ['Adventure', 'Comedy', 'Family'],
        language: ['English', 'Hindi'],
        duration: 115,
        certification: 'U',
        releaseDate: new Date('2026-09-04'),
        cast: ['Jason Momoa', 'Jack Black', 'Danielle Brooks'],
        director: 'Jared Hess',
        rating: 3.8,
        ratingCount: 700,
        status: 'now-showing',
        formats: ['2D', '3D'],
        source: 'seed',
        viewCount: 18900,
        country: 'US',
      },
      {
        title: 'Mission: Impossible - The Final Reckoning',
        description: 'Ethan Hunt faces the most dangerous foe yet in what could be his ultimate mission.',
        poster: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg',
        trailerUrl: '',
        genre: ['Action', 'Adventure', 'Thriller'],
        language: ['English', 'Hindi', 'Telugu'],
        duration: 163,
        certification: 'UA',
        releaseDate: new Date('2026-09-12'),
        cast: ['Tom Cruise', 'Hayley Atwell', 'Simon Pegg', 'Vanessa Kirby'],
        director: 'Christopher McQuarrie',
        rating: 4.8,
        ratingCount: 1500,
        status: 'now-showing',
        formats: ['2D', 'IMAX', '4DX'],
        source: 'seed',
        isFeatured: true,
        isTrending: true,
        viewCount: 62400,
        country: 'US',
      },

      // ── NEW RELEASES (last 3 days) ────────────────────────
      {
        title: 'Akhanda 2',
        description: 'The ferocious Aghora warrior Akhanda returns to battle an ancient evil threatening all of humanity.',
        poster: 'https://image.tmdb.org/t/p/w500/rO3sDaLnXuU6QPLEd00f7i8b3c4.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/bVTrOWjGLu6dS5ZrXRQ0j0GHeJA.jpg',
        trailerUrl: '',
        genre: ['Action', 'Fantasy', 'Drama'],
        language: ['Telugu'],
        originalLanguage: 'Telugu',
        industry: 'Tollywood',
        languages: ['Telugu', 'Hindi'],
        duration: 165,
        certification: 'UA',
        releaseDate: new Date('2026-09-18'),
        cast: ['Nandamuri Balakrishna', 'Bobby Deol', 'Pragya Jaiswal'],
        director: 'Boyapati Srinu',
        rating: 4.0,
        ratingCount: 200,
        status: 'now-showing',
        formats: ['2D', '3D', 'IMAX'],
        source: 'seed',
        viewCount: 8900,
        country: 'IN',
      },
      {
        title: 'Sikandar Ka Muqaddar',
        description: 'A gritty crime drama about an underdog from the streets of Mumbai who rises through sheer willpower.',
        poster: 'https://image.tmdb.org/t/p/w500/4cR2qVBqMHjO6RHGx6W1RZyxKz2.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/zK3aG3p8cUjfXl0rOKaQeM1bwXv.jpg',
        trailerUrl: '',
        genre: ['Crime', 'Drama', 'Thriller'],
        language: ['Hindi'],
        originalLanguage: 'Hindi',
        industry: 'Bollywood',
        languages: ['Hindi'],
        duration: 142,
        certification: 'A',
        releaseDate: new Date('2026-09-19'),
        cast: ['Jimmy Shergill', 'Avinash Tiwary', 'Tamannaah Bhatia'],
        director: 'Neeraj Pandey',
        rating: 3.9,
        ratingCount: 100,
        status: 'now-showing',
        formats: ['2D'],
        source: 'seed',
        viewCount: 4200,
        country: 'IN',
      },
      {
        title: 'Lucky Bhaskar',
        description: 'A mild-mannered bank employee stumbles into a life of extraordinary fortune and danger in this dark comedy thriller.',
        poster: 'https://image.tmdb.org/t/p/w500/7qlcz0VlQu4K7xYmq3T4SH5bUHt.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/q5Sw9c22YBtRmrJdL8SCqCQdPjY.jpg',
        trailerUrl: '',
        genre: ['Comedy', 'Thriller', 'Drama'],
        language: ['Telugu'],
        originalLanguage: 'Telugu',
        industry: 'Tollywood',
        languages: ['Telugu', 'Hindi'],
        duration: 150,
        certification: 'UA',
        releaseDate: new Date('2026-09-17'),
        cast: ['Dulquer Salmaan', 'Meenakshi Chaudhary', 'Hyper Aadi'],
        director: 'Venky Atluri',
        rating: 4.5,
        ratingCount: 350,
        status: 'now-showing',
        formats: ['2D'],
        source: 'seed',
        isTrending: true,
        viewCount: 12800,
        country: 'IN',
      },

      // ── UPCOMING / COMING SOON ─────────────────────────────
      {
        title: 'Avatar: Fire and Ash',
        description: 'Jake Sully and Neytiri encounter a new, aggressive clan of Na\'vi known as the Ash People who reside around volcanic regions.',
        poster: 'https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/vL5LR6WdxWPjC3754h62c9Tqg.jpg',
        trailerUrl: 'https://www.youtube.com/watch?v=d9MyW72ELq0',
        genre: ['Sci-Fi', 'Action', 'Adventure'],
        language: ['English', 'Hindi', 'Telugu'],
        duration: 190,
        certification: 'UA',
        releaseDate: new Date('2026-12-19'),
        cast: ['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver', 'Oona Chaplin'],
        director: 'James Cameron',
        rating: 4.9,
        ratingCount: 0,
        status: 'coming-soon',
        formats: ['3D', 'IMAX', '4DX'],
        source: 'seed',
        isFeatured: true,
        viewCount: 71200,
        country: 'US',
      },
      {
        title: 'Spider-Man: Beyond the Spider-Verse',
        description: 'Miles Morales traverses alternate dimensions to save every universe\'s Spider-People from a catastrophic multiverse collapse.',
        poster: 'https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg',
        trailerUrl: 'https://www.youtube.com/watch?v=cqGjhVJWtEg',
        genre: ['Animation', 'Action', 'Sci-Fi'],
        language: ['English', 'Hindi', 'Telugu', 'Tamil'],
        duration: 140,
        certification: 'U',
        releaseDate: new Date('2026-12-12'),
        cast: ['Shameik Moore', 'Hailee Steinfeld', 'Oscar Isaac', 'Daniel Kaluuya'],
        director: 'Joaquim Dos Santos',
        rating: 5.0,
        ratingCount: 0,
        status: 'coming-soon',
        formats: ['2D', '3D', 'IMAX'],
        source: 'seed',
        isFeatured: true,
        viewCount: 45600,
        country: 'US',
      },
      {
        title: 'Pushpa 3: The Rampage',
        description: 'Pushpa Raj faces his most lethal enemy yet as the red sandalwood smuggling empire comes under siege from a nationwide crackdown.',
        poster: 'https://image.tmdb.org/t/p/w500/b0OnvU5xV5xZ2K2QYgL9uU1dI9c.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/9wSbeLhhQvE8uG020R4R0pLzWw1.jpg',
        trailerUrl: '',
        genre: ['Action', 'Crime', 'Drama'],
        language: ['Telugu', 'Hindi', 'Tamil', 'Malayalam', 'Kannada'],
        duration: 195,
        certification: 'UA',
        releaseDate: new Date('2027-04-15'),
        cast: ['Allu Arjun', 'Rashmika Mandanna', 'Fahadh Faasil'],
        director: 'Sukumar',
        rating: 0,
        ratingCount: 0,
        status: 'coming-soon',
        formats: ['2D', '3D', 'IMAX'],
        source: 'seed',
        viewCount: 92100,
        country: 'IN',
      },
      {
        title: 'RRR 2',
        description: 'The explosive sequel to the global phenomenon continues the fictional tales of revolutionary heroes Alluri Sitarama Raju and Komaram Bheem.',
        poster: 'https://image.tmdb.org/t/p/w500/nEufeZYoDBPKdBc3H34gVZKebe4.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/5GbkL9DDRzq3A21nR7gZnMM1rv2.jpg',
        trailerUrl: '',
        genre: ['Action', 'Drama', 'Historical'],
        language: ['Telugu', 'Hindi', 'Tamil', 'Malayalam', 'Kannada', 'English'],
        duration: 190,
        certification: 'UA',
        releaseDate: new Date('2027-01-26'),
        cast: ['Ram Charan', 'Jr NTR', 'Alia Bhatt'],
        director: 'S.S. Rajamouli',
        rating: 0,
        ratingCount: 0,
        status: 'coming-soon',
        formats: ['2D', '3D', 'IMAX', '4DX'],
        source: 'seed',
        isFeatured: true,
        viewCount: 128500,
        country: 'IN',
      },
      {
        title: 'Brahmastra Part 2: Dev',
        description: 'The story of Dev and the origin of the first Astraverse unfolds in this mythological fantasy sequel.',
        poster: 'https://image.tmdb.org/t/p/w500/c2UQ5R0s4nVWvEEE1zrXO3Mn10U.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/pTlwPfJQjOhoBnyAJK3jez3z3z3.jpg',
        trailerUrl: '',
        genre: ['Fantasy', 'Action', 'Adventure'],
        language: ['Hindi'],
        originalLanguage: 'Hindi',
        industry: 'Bollywood',
        languages: ['Hindi'],
        duration: 170,
        certification: 'UA',
        releaseDate: new Date('2027-03-15'),
        cast: ['Ranbir Kapoor', 'Deepika Padukone', 'Ranveer Singh'],
        director: 'Ayan Mukerji',
        rating: 0,
        ratingCount: 0,
        status: 'coming-soon',
        formats: ['2D', '3D', 'IMAX'],
        source: 'seed',
        viewCount: 35800,
        country: 'IN',
      },
      {
        title: 'Baahubali 3',
        description: 'The next chapter in the legendary Baahubali saga takes the kingdom of Mahishmati to new frontiers.',
        poster: 'https://image.tmdb.org/t/p/w500/dOGMwCgfGMKKx5RVGFmHSutwqfq.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/bQS43HSLZzMjZkcHJz4fGc3DMHB.jpg',
        trailerUrl: '',
        genre: ['Action', 'Fantasy', 'Drama'],
        language: ['Telugu', 'Hindi', 'Tamil', 'Malayalam', 'Kannada'],
        duration: 200,
        certification: 'UA',
        releaseDate: new Date('2027-07-10'),
        cast: ['Prabhas', 'Anushka Shetty', 'Rana Daggubati', 'Tamannah Bhatia'],
        director: 'S.S. Rajamouli',
        rating: 0,
        ratingCount: 0,
        status: 'coming-soon',
        formats: ['2D', '3D', 'IMAX', '4DX'],
        source: 'seed',
        isFeatured: true,
        viewCount: 156000,
        country: 'IN',
      },
      {
        title: 'KGF: Chapter 3',
        description: 'The final chapter of Rocky Bhai\'s empire. The gold mines. The power. The legend concludes.',
        poster: 'https://image.tmdb.org/t/p/w500/hkBq0O3aAwfnPjMCqH3MG8WR0lq.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/vR8bJfSXmTY6KfNk08QMvIBrOHE.jpg',
        trailerUrl: '',
        genre: ['Action', 'Drama', 'Crime'],
        language: ['Kannada', 'Telugu', 'Hindi', 'Tamil', 'Malayalam'],
        duration: 180,
        certification: 'UA',
        releaseDate: new Date('2027-02-20'),
        cast: ['Yash', 'Srinidhi Shetty', 'Raveena Tandon'],
        director: 'Prashanth Neel',
        rating: 0,
        ratingCount: 0,
        status: 'coming-soon',
        formats: ['2D', '3D', 'IMAX'],
        source: 'seed',
        viewCount: 89700,
        country: 'IN',
      },
      {
        title: 'Don 3',
        description: 'The king of the underworld returns. This time, Don takes on an international syndicate in a deadly game of power.',
        poster: 'https://image.tmdb.org/t/p/w500/6Wdl9N9dOJXgEKtu0P4PyAgbtHj.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/wNXMDOxNOB8lXQ3o0fYVEFxMJdE.jpg',
        trailerUrl: '',
        genre: ['Action', 'Thriller', 'Crime'],
        language: ['Hindi'],
        originalLanguage: 'Hindi',
        industry: 'Bollywood',
        languages: ['Hindi'],
        duration: 155,
        certification: 'UA',
        releaseDate: new Date('2026-12-25'),
        cast: ['Ranveer Singh', 'Kiara Advani'],
        director: 'Farhan Akhtar',
        rating: 0,
        ratingCount: 0,
        status: 'coming-soon',
        formats: ['2D', '3D', 'IMAX'],
        source: 'seed',
        viewCount: 42300,
        country: 'IN',
      },
      {
        title: 'The Batman Part II',
        description: 'Bruce Wayne delves deeper into Gotham City\'s corruption as The Riddler\'s legacy inspires new villains.',
        poster: 'https://image.tmdb.org/t/p/w500/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/euYIwmwkmz95mnXvufEmbL69ovr.jpg',
        trailerUrl: '',
        genre: ['Action', 'Crime', 'Mystery'],
        language: ['English', 'Hindi'],
        duration: 175,
        certification: 'UA',
        releaseDate: new Date('2026-10-01'),
        cast: ['Robert Pattinson', 'Zoe Kravitz', 'Barry Keoghan'],
        director: 'Matt Reeves',
        rating: 0,
        ratingCount: 0,
        status: 'coming-soon',
        formats: ['2D', 'IMAX', '4DX'],
        source: 'seed',
        viewCount: 53200,
        country: 'US',
      },
      {
        title: 'Fantastic Four: First Steps',
        description: 'Marvel\'s first family finally arrives in the MCU, facing the cosmic threat of Galactus.',
        poster: 'https://image.tmdb.org/t/p/w500/mifGKiCGRsu39V6zNxFSXzE3UNl.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
        trailerUrl: '',
        genre: ['Action', 'Adventure', 'Sci-Fi'],
        language: ['English', 'Hindi', 'Telugu', 'Tamil'],
        duration: 145,
        certification: 'UA',
        releaseDate: new Date('2026-11-07'),
        cast: ['Pedro Pascal', 'Vanessa Kirby', 'Joseph Quinn', 'Ebon Moss-Bachrach'],
        director: 'Matt Shakman',
        rating: 0,
        ratingCount: 0,
        status: 'coming-soon',
        formats: ['2D', '3D', 'IMAX'],
        source: 'seed',
        viewCount: 38400,
        country: 'US',
      },

      // ── ENDED (archive-worthy, for booking history) ────────
      {
        title: 'RRR',
        description: 'A fictional story about two Indian revolutionaries who fought against the British Raj.',
        poster: 'https://image.tmdb.org/t/p/w500/nEufeZYoDBPKdBc3H34gVZKebe4.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/5GbkL9DDRzq3A21nR7gZnMM1rv2.jpg',
        trailerUrl: 'https://www.youtube.com/watch?v=f_vbAtFSEc0',
        genre: ['Action', 'Drama', 'Historical'],
        language: ['Telugu'],
        originalLanguage: 'Telugu',
        industry: 'Tollywood',
        languages: ['Telugu', 'Hindi'],
        duration: 187,
        certification: 'UA',
        releaseDate: new Date('2022-03-25'),
        cast: ['Ram Charan', 'Jr NTR', 'Alia Bhatt', 'Ajay Devgn'],
        director: 'S.S. Rajamouli',
        rating: 4.9,
        ratingCount: 8500,
        status: 'ended',
        formats: ['2D', '3D'],
        source: 'seed',
        viewCount: 210000,
        country: 'IN',
      },
      {
        title: 'Baahubali 2: The Conclusion',
        description: 'When Shivudu learns about his true heritage, he begins to fight for justice against Bhallaladeva.',
        poster: 'https://image.tmdb.org/t/p/w500/dOGMwCgfGMKKx5RVGFmHSutwqfq.jpg',
        backdrop: 'https://image.tmdb.org/t/p/original/bQS43HSLZzMjZkcHJz4fGc3DMHB.jpg',
        trailerUrl: 'https://www.youtube.com/watch?v=G62HrubdD6o',
        genre: ['Action', 'Drama', 'Fantasy'],
        language: ['Telugu'],
        originalLanguage: 'Telugu',
        industry: 'Tollywood',
        languages: ['Telugu', 'Hindi'],
        duration: 167,
        certification: 'UA',
        releaseDate: new Date('2017-04-28'),
        cast: ['Prabhas', 'Anushka Shetty', 'Rana Daggubati', 'Sathyaraj'],
        director: 'S.S. Rajamouli',
        rating: 5.0,
        ratingCount: 12000,
        status: 'ended',
        formats: ['2D', '3D'],
        source: 'seed',
        viewCount: 350000,
        country: 'IN',
      },
    ];

    const createdMovies = await Movie.insertMany(enrichWithIMDbData(moviesData));
    console.log(`[Seed] Seeded ${createdMovies.length} movies.`);

    console.log('[Seed] Seeding Theatres...');
    const theatresData = [
      {
        name: 'SmartCine PVR IMAX – Inorbit Mall',
        address: 'Level 4, Inorbit Mall, Mindspace, Madhapur',
        city: 'Hyderabad',
        location: { lat: 17.4356, lng: 78.3844 },
        amenities: ['IMAX with Laser', 'Dolby Atmos', 'Recliner Seats', 'Gourmet Food Court', 'Valet Parking'],
        contactInfo: { phone: '+91 40 6789 1100', email: 'inorbit.hyd@smartcine.com' },
        isActive: true,
      },
      {
        name: 'SmartCine AMB Cinemas – Gachibowli',
        address: 'Sarath City Capital Mall, Gachibowli - Miyapur Rd',
        city: 'Hyderabad',
        location: { lat: 17.4589, lng: 78.3582 },
        amenities: ['Dolby Atmos', 'Laser Projection', 'VIP Lounge', 'Gourmet Popcorn', 'Ample Parking'],
        contactInfo: { phone: '+91 40 4455 6677', email: 'amb.hyd@smartcine.com' },
        isActive: true,
      },
      {
        name: 'SmartCine Prasads Multiplex – NTR Gardens',
        address: 'Necklace Road, Khairatabad',
        city: 'Hyderabad',
        location: { lat: 17.4125, lng: 78.4682 },
        amenities: ['Giant Screen', 'Dolby 7.1', 'Gaming Arena', 'Food Court', 'Waterfront View'],
        contactInfo: { phone: '+91 40 2344 8888', email: 'prasads.hyd@smartcine.com' },
        isActive: true,
      },
      {
        name: 'SmartCine Director\'s Cut – Forum Rex Walk',
        address: 'Brigade Road, Shanthala Nagar, Ashok Nagar',
        city: 'Bengaluru',
        location: { lat: 12.9716, lng: 77.5946 },
        amenities: ['Luxury Recliners', 'In-Seat Chef Service', 'Dolby Atmos', 'Premium Wine Bar'],
        contactInfo: { phone: '+91 80 4123 5566', email: 'directorscut.blr@smartcine.com' },
        isActive: true,
      },
      {
        name: 'SmartCine Maison INOX – Jio World Plaza',
        address: 'G Block, Bandra Kurla Complex, Bandra East',
        city: 'Mumbai',
        location: { lat: 19.0668, lng: 72.8687 },
        amenities: ['IMAX Laser', 'Private Screening Rooms', 'Butler Service', 'Dolby Atmos 360'],
        contactInfo: { phone: '+91 22 6677 8899', email: 'maison.mum@smartcine.com' },
        isActive: true,
      },
      {
        name: 'SmartCine Cinepolis – PVP Square',
        address: 'MG Road, Sidhartha Nagar',
        city: 'Vijayawada',
        location: { lat: 16.5062, lng: 80.648 },
        amenities: ['RealD 3D', 'Dolby 7.1', 'Coffee House', 'Food Court'],
        contactInfo: { phone: '+91 866 244 5566', email: 'pvp.vja@smartcine.com' },
        isActive: true,
      },
      {
        name: 'SmartCine Jagadamba Prime',
        address: 'Jagadamba Junction, Suryabagh',
        city: 'Visakhapatnam',
        location: { lat: 17.7126, lng: 83.3005 },
        amenities: ['Dolby Atmos', '70mm Large Screen', 'Curved Display', 'Cafeteria'],
        contactInfo: { phone: '+91 891 256 7890', email: 'jagadamba.vizag@smartcine.com' },
        isActive: true,
      },
    ];

    const createdTheatres = await Theatre.insertMany(theatresData);

    console.log('[Seed] Seeding Screens and Seat Maps...');
    const defaultSeatLayout = {
      rows: [
        { rowLabel: 'A', category: 'Premium', seatsCount: 10, priceMultiplier: 1.5 },
        { rowLabel: 'B', category: 'Premium', seatsCount: 10, priceMultiplier: 1.5 },
        { rowLabel: 'C', category: 'Executive', seatsCount: 10, priceMultiplier: 1.25 },
        { rowLabel: 'D', category: 'Executive', seatsCount: 10, priceMultiplier: 1.25 },
        { rowLabel: 'E', category: 'Regular', seatsCount: 10, priceMultiplier: 1.0 },
        { rowLabel: 'F', category: 'Regular', seatsCount: 10, priceMultiplier: 1.0 },
        { rowLabel: 'G', category: 'Regular', seatsCount: 10, priceMultiplier: 1.0 },
        { rowLabel: 'H', category: 'Regular', seatsCount: 10, priceMultiplier: 1.0 },
      ],
    };

    const imaxSeatLayout = {
      rows: [
        { rowLabel: 'A', category: 'Premium', seatsCount: 12, priceMultiplier: 1.6 },
        { rowLabel: 'B', category: 'Premium', seatsCount: 12, priceMultiplier: 1.6 },
        { rowLabel: 'C', category: 'Executive', seatsCount: 12, priceMultiplier: 1.3 },
        { rowLabel: 'D', category: 'Executive', seatsCount: 12, priceMultiplier: 1.3 },
        { rowLabel: 'E', category: 'Regular', seatsCount: 12, priceMultiplier: 1.0 },
        { rowLabel: 'F', category: 'Regular', seatsCount: 12, priceMultiplier: 1.0 },
      ],
    };

    const createdScreens = [];
    const seatsToInsert = [];

    for (const theatre of createdTheatres) {
      const screen1 = await Screen.create({
        theatreId: theatre._id,
        name: 'Screen 1 (IMAX Laser)',
        format: 'IMAX',
        capacity: 72,
        soundSystem: 'IMAX 12-Channel Immersive Sound',
        seatLayout: imaxSeatLayout,
      });
      createdScreens.push(screen1);

      for (const rowConfig of imaxSeatLayout.rows) {
        for (let num = 1; num <= rowConfig.seatsCount; num++) {
          seatsToInsert.push({
            screenId: screen1._id,
            row: rowConfig.rowLabel,
            number: num,
            category: rowConfig.category,
            priceMultiplier: rowConfig.priceMultiplier,
            isActive: true,
          });
        }
      }

      const screen2 = await Screen.create({
        theatreId: theatre._id,
        name: 'Screen 2 (Dolby Atmos)',
        format: '3D',
        capacity: 80,
        soundSystem: 'Dolby Atmos 7.1 Surround',
        seatLayout: defaultSeatLayout,
      });
      createdScreens.push(screen2);

      for (const rowConfig of defaultSeatLayout.rows) {
        for (let num = 1; num <= rowConfig.seatsCount; num++) {
          seatsToInsert.push({
            screenId: screen2._id,
            row: rowConfig.rowLabel,
            number: num,
            category: rowConfig.category,
            priceMultiplier: rowConfig.priceMultiplier,
            isActive: true,
          });
        }
      }

      const screen3 = await Screen.create({
        theatreId: theatre._id,
        name: 'Screen 3 (Standard 2D)',
        format: '2D',
        capacity: 80,
        soundSystem: 'Dolby Digital 5.1',
        seatLayout: defaultSeatLayout,
      });
      createdScreens.push(screen3);

      for (const rowConfig of defaultSeatLayout.rows) {
        for (let num = 1; num <= rowConfig.seatsCount; num++) {
          seatsToInsert.push({
            screenId: screen3._id,
            row: rowConfig.rowLabel,
            number: num,
            category: rowConfig.category,
            priceMultiplier: rowConfig.priceMultiplier,
            isActive: true,
          });
        }
      }
    }

    await Seat.insertMany(seatsToInsert);
    console.log(`[Seed] Seeded ${createdScreens.length} screens and ${seatsToInsert.length} configured seats.`);

    console.log('[Seed] Seeding Shows for the upcoming 7 days...');
    const upcomingDates = [];
    for (let i = 0; i < 7; i++) {
      const d = new Date();
      d.setDate(d.getDate() + i);
      upcomingDates.push(d.toISOString().split('T')[0]);
    }

    const showtimes = [
      { start: '10:30', end: '13:30' },
      { start: '14:15', end: '17:15' },
      { start: '18:00', end: '21:00' },
      { start: '21:45', end: '00:45' },
    ];

    const showsToInsert = [];
    const nowShowingMovies = createdMovies.filter((m) => m.status === 'now-showing');

    for (const theatre of createdTheatres) {
      const theatreScreens = createdScreens.filter((s) => s.theatreId.toString() === theatre._id.toString());

      for (const dateStr of upcomingDates) {
        for (let screenIdx = 0; screenIdx < theatreScreens.length; screenIdx++) {
          const screen = theatreScreens[screenIdx];
          const movie = nowShowingMovies[(theatreScreens.indexOf(screen) + upcomingDates.indexOf(dateStr)) % nowShowingMovies.length];

          for (let timeIdx = 0; timeIdx < showtimes.length; timeIdx++) {
            const timeSlot = showtimes[timeIdx];
            const basePrice = screen.format === 'IMAX' ? 350 : screen.format === '3D' ? 250 : 200;

            const prebooked = [];
            if (timeIdx === 2 || timeIdx === 3) {
              prebooked.push('A-3', 'A-4', 'B-5', 'B-6', 'C-7', 'C-8', 'D-4', 'D-5');
            }

            showsToInsert.push({
              movieId: movie._id,
              theatreId: theatre._id,
              screenId: screen._id,
              date: dateStr,
              startTime: timeSlot.start,
              endTime: timeSlot.end,
              language: movie.language[0] || 'English',
              format: screen.format,
              basePrice,
              status: 'scheduled',
              bookedSeats: prebooked,
            });
          }
        }
      }
    }

    const createdShows = await Show.insertMany(showsToInsert);
    console.log(`[Seed] Seeded ${createdShows.length} showtimes.`);

    console.log('[Seed] Seeding Coupons...');
    const couponsData = [
      {
        code: 'SMARTCINE10',
        description: 'Get 10% instant discount up to ₹100 on all bookings',
        discountType: 'percentage',
        discountValue: 10,
        minimumAmount: 300,
        maximumDiscount: 100,
        validFrom: new Date(),
        validUntil: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
        usageLimit: 5000,
        usedCount: 42,
        isActive: true,
      },
      {
        code: 'BLOCKBUSTER50',
        description: 'Flat ₹50 OFF on any movie booking of ₹400 or more',
        discountType: 'fixed',
        discountValue: 50,
        minimumAmount: 400,
        maximumDiscount: 50,
        validFrom: new Date(),
        validUntil: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
        usageLimit: 2000,
        usedCount: 88,
        isActive: true,
      },
      {
        code: 'IMAXPASS',
        description: 'Get 20% discount up to ₹150 on premium IMAX experiences',
        discountType: 'percentage',
        discountValue: 20,
        minimumAmount: 500,
        maximumDiscount: 150,
        validFrom: new Date(),
        validUntil: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
        usageLimit: 1000,
        usedCount: 29,
        isActive: true,
      },
      {
        code: 'WELCOME100',
        description: 'Exclusive ₹100 instant discount on your first SmartCine ticket',
        discountType: 'fixed',
        discountValue: 100,
        minimumAmount: 500,
        maximumDiscount: 100,
        validFrom: new Date(),
        validUntil: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
        usageLimit: 10000,
        usedCount: 156,
        isActive: true,
      },
    ];

    await Coupon.insertMany(couponsData);

    console.log('[Seed] Seeding Sample Bookings & Payments for Analytics...');
    const firstShow = createdShows[0];
    const secondShow = createdShows[1];

    const ref1 = generateBookingReference();
    const qr1 = await generateQRCode({
      bookingReference: ref1,
      movie: createdMovies[0].title,
      seats: ['A-1', 'A-2'],
      theatre: 'SmartCine PVR IMAX – Inorbit Mall',
    });

    const booking1 = await Booking.create({
      userId: customer._id,
      showId: firstShow._id,
      movieId: firstShow.movieId,
      theatreId: firstShow.theatreId,
      screenId: firstShow.screenId,
      seats: [
        { seatId: 'A-1', row: 'A', number: 1, category: 'Premium', price: 525 },
        { seatId: 'A-2', row: 'A', number: 2, category: 'Premium', price: 525 },
      ],
      subtotal: 1050,
      convenienceFee: 40,
      tax: 55,
      discount: 100,
      couponCode: 'SMARTCINE10',
      totalAmount: 1045,
      paymentStatus: 'paid',
      bookingStatus: 'confirmed',
      bookingReference: ref1,
      qrCode: qr1,
    });

    await Payment.create({
      bookingId: booking1._id,
      userId: customer._id,
      provider: 'SmartCinePay',
      providerOrderId: `order_${ref1}`,
      providerPaymentId: `pay_${ref1}`,
      amount: 1045,
      paymentMethod: 'UPI',
      status: 'captured',
    });

    const ref2 = generateBookingReference();
    const qr2 = await generateQRCode({
      bookingReference: ref2,
      movie: createdMovies[1].title,
      seats: ['C-1', 'C-2', 'C-3'],
      theatre: 'SmartCine AMB Cinemas – Gachibowli',
    });

    const booking2 = await Booking.create({
      userId: customer2._id,
      showId: secondShow._id,
      movieId: secondShow.movieId,
      theatreId: secondShow.theatreId,
      screenId: secondShow.screenId,
      seats: [
        { seatId: 'C-1', row: 'C', number: 1, category: 'Executive', price: 312 },
        { seatId: 'C-2', row: 'C', number: 2, category: 'Executive', price: 312 },
        { seatId: 'C-3', row: 'C', number: 3, category: 'Executive', price: 312 },
      ],
      subtotal: 936,
      convenienceFee: 40,
      tax: 49,
      discount: 50,
      couponCode: 'BLOCKBUSTER50',
      totalAmount: 975,
      paymentStatus: 'paid',
      bookingStatus: 'confirmed',
      bookingReference: ref2,
      qrCode: qr2,
    });

    await Payment.create({
      bookingId: booking2._id,
      userId: customer2._id,
      provider: 'SmartCinePay',
      providerOrderId: `order_${ref2}`,
      providerPaymentId: `pay_${ref2}`,
      amount: 975,
      paymentMethod: 'CARD',
      status: 'captured',
    });

    console.log('[Seed] Seeding Reviews...');
    await Review.create([
      {
        userId: customer._id,
        movieId: createdMovies[0]._id,
        bookingId: booking1._id,
        rating: 5,
        comment: 'Mind-blowing visuals and cinematic world-building! Allu Arjun gave a legendary performance.',
        status: 'approved',
        likes: 24,
      },
      {
        userId: customer2._id,
        movieId: createdMovies[1]._id,
        bookingId: booking2._id,
        rating: 5,
        comment: 'An absolute masterpiece of action cinema. The coastal scenes and fight choreography gave me goosebumps!',
        status: 'approved',
        likes: 41,
      },
      {
        userId: customer._id,
        movieId: createdMovies[2]._id,
        rating: 5,
        comment: 'Visually stunning! Nag Ashwin created an incredible world. Prabhas and Amitabh Bachchan are phenomenal together.',
        status: 'approved',
        likes: 19,
      },
    ]);

    console.log('✅ [Seed] SmartCine Database successfully initialized with 55+ movies and rich demo data!');
    console.log('------------------------------------------------------------');
    console.log('Admin Demo:    admin@smartcine.com    | Password: Admin@12345');
    console.log('Customer Demo: customer@smartcine.com | Password: Customer@12345');
    console.log('------------------------------------------------------------');
    if (isStandalone) {
      process.exit(0);
    }
    return true;
  } catch (error) {
    console.error('❌ [Seed] Error seeding database:', error);
    if (isStandalone) {
      process.exit(1);
    }
    throw error;
  }
};

export { seedDatabase };

if (process.argv[1]?.endsWith('seedData.js')) {
  seedDatabase(true);
}
